### ISSUE TITLE
Deployment activisme.be

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/activisme.be#13]
**DEPLOY:** 02:00h 07/04/2017. 

**TODO:** 

- [x] New version for the repo 
- [x] New version for the new file (Needed for the compatibility break). 
- [x] Crowdfund readme need a deprecated note. (Data rendation: 1 year). 

NOTE: files located in skype

Follow up: @alfamongrel
